"""add progress_log table

Revision ID: 6446a7afbd9a
Revises: 20260319_add_handoff_request
Create Date: 2026-04-16 18:34:40.712275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6446a7afbd9a'
down_revision = '20260319_add_handoff_request'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('metric', sa.String(length=80), nullable=True),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_log_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_sender_id'))

    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intent_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('progress_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_progress_log_sender_id'))

    op.drop_table('progress_log')
    # ### end Alembic commands ###
