"""add fitness classes

Revision ID: b6a0482aab51
Revises: 20251210_add_google_auth_columns
Create Date: 2025-12-22 00:08:41.077370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6a0482aab51'
down_revision = '20251210_add_google_auth_columns'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructor', sa.String(length=120), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('capacity >= 0', name='ck_fitness_class_capacity_nonneg'),
    sa.CheckConstraint('duration_min > 0', name='ck_fitness_class_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fitness_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fitness_class_name'), ['name'], unique=False)

    op.create_table('class_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration_override', sa.Integer(), nullable=True),
    sa.Column('capacity_override', sa.Integer(), nullable=True),
    sa.Column('is_exclusive', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('capacity_override IS NULL OR capacity_override >= 0', name='ck_class_session_capacity_nonneg'),
    sa.CheckConstraint('duration_override IS NULL OR duration_override > 0', name='ck_class_session_duration_positive'),
    sa.ForeignKeyConstraint(['class_id'], ['fitness_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_session_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_session_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_session_start_time'))
        batch_op.drop_index(batch_op.f('ix_class_session_class_id'))

    op.drop_table('class_session')
    with op.batch_alter_table('fitness_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitness_class_name'))

    op.drop_table('fitness_class')
    # ### end Alembic commands ###
