"""fitter_inicial

Revision ID: 84be7e824a9e
Revises: 
Create Date: 2025-09-27 16:18:58.850747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84be7e824a9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categoria_nombre'), ['nombre'], unique=True)

    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('imagen_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('precio >= 0', name='ck_producto_precio_nonneg'),
    sa.CheckConstraint('stock >= 0', name='ck_producto_stock_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_nombre'), ['nombre'], unique=False)

    op.create_table('producto_categoria',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_categoria')
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_nombre'))
        batch_op.drop_index(batch_op.f('ix_producto_created_at'))
        batch_op.drop_index(batch_op.f('ix_producto_categoria'))

    op.drop_table('producto')
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_nombre'))

    op.drop_table('categoria')
    # ### end Alembic commands ###
